# Docker Compose for AI Email Categorization System
version: '3.8'

services:
  # Main email categorization service
  email-categorizer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-1.2.0}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
    image: email-categorizer:latest
    container_name: email-categorizer-main
    restart: unless-stopped
    
    # Environment variables
    environment:
      - TZ=Africa/Johannesburg
      - PYTHONUNBUFFERED=1
      - CATEGORIZER_MODE=continuous
      - CHECK_INTERVAL=300
    
    # Mount configuration and logs
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./logs:/app/logs
      - categorizer-data:/app/data
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Networks
    networks:
      - emailcat-network

  # Web Interface Service
  web-interface:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-categorizer:latest
    container_name: email-categorizer-web
    restart: unless-stopped
    
    environment:
      - TZ=Africa/Johannesburg
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - PORT=8082
    
    volumes:
      - ./config.ini:/app/config.ini
      - ./logs:/app/logs
    
    ports:
      - "8082:8082"
    
    command: ["python3", "web_interface.py"]
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    depends_on:
      - email-categorizer
    
    networks:
      - emailcat-network

  # Optional: Manual execution service (for one-time runs)
  email-categorizer-manual:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-categorizer:latest
    container_name: email-categorizer-manual
    profiles: ["manual"]  # Only start when explicitly requested
    
    environment:
      - TZ=Africa/Johannesburg
      - PYTHONUNBUFFERED=1
    
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./logs:/app/logs
    
    command: ["python3", "email_categorizer.py"]
    
    networks:
      - emailcat-network

  # Optional: Dry run service (for testing)
  email-categorizer-dryrun:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-categorizer:latest
    container_name: email-categorizer-dryrun
    profiles: ["dryrun"]  # Only start when explicitly requested
    
    environment:
      - TZ=Africa/Johannesburg
      - PYTHONUNBUFFERED=1
    
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./logs:/app/logs
    
    command: ["python3", "email_categorizer_dry_run.py", "ALL", "5"]
    
    networks:
      - emailcat-network

  # Prometheus Metrics Collection
  prometheus:
    image: prom/prometheus:latest
    container_name: email-categorizer-prometheus
    profiles: ["monitoring"]
    restart: unless-stopped
    
    ports:
      - "9090:9090"
    
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    
    networks:
      - emailcat-network

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: email-categorizer-grafana
    profiles: ["monitoring"]
    restart: unless-stopped
    
    ports:
      - "3000:3000"
    
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=emailcat_admin
      - GF_USERS_ALLOW_SIGN_UP=false
    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    
    depends_on:
      - prometheus
    
    networks:
      - emailcat-network

  # Container Metrics (cAdvisor)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: email-categorizer-cadvisor
    profiles: ["monitoring"]
    restart: unless-stopped
    
    ports:
      - "8080:8080"
    
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    
    privileged: true
    devices:
      - /dev/kmsg
    
    networks:
      - emailcat-network

  # Node Exporter (System Metrics)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: email-categorizer-node-exporter
    profiles: ["monitoring"]
    restart: unless-stopped
    
    ports:
      - "9100:9100"
    
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    
    networks:
      - emailcat-network

  # Loki (Log Aggregation)
  loki:
    image: grafana/loki:latest
    container_name: email-categorizer-loki
    profiles: ["monitoring"]
    restart: unless-stopped
    
    ports:
      - "3100:3100"
    
    volumes:
      - ./monitoring/loki/loki.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    
    command: -config.file=/etc/loki/local-config.yaml
    
    networks:
      - emailcat-network

  # Promtail (Log Shipping)
  promtail:
    image: grafana/promtail:latest
    container_name: email-categorizer-promtail
    profiles: ["monitoring"]
    restart: unless-stopped
    
    volumes:
      - ./monitoring/promtail/promtail.yml:/etc/promtail/config.yml:ro
      - ./logs:/var/log/email-categorizer:ro
      - /var/log:/var/log/host:ro
    
    command: -config.file=/etc/promtail/config.yml
    
    depends_on:
      - loki
    
    networks:
      - emailcat-network

  # AlertManager (Alerting)
  alertmanager:
    image: prom/alertmanager:latest
    container_name: email-categorizer-alertmanager
    profiles: ["monitoring"]
    restart: unless-stopped
    
    ports:
      - "9093:9093"
    
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    
    networks:
      - emailcat-network

  # Metrics Exporter (Custom Application Metrics)
  metrics-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-categorizer:latest
    container_name: email-categorizer-metrics
    profiles: ["monitoring"]
    restart: unless-stopped
    
    environment:
      - TZ=Africa/Johannesburg
      - PYTHONUNBUFFERED=1
      - METRICS_PORT=8000
    
    ports:
      - "8000:8000"
    
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./logs:/app/logs:ro
    
    command: ["python3", "api_monitor.py", "--serve-metrics"]
    
    depends_on:
      - email-categorizer
    
    networks:
      - emailcat-network

# Named volumes for data persistence
volumes:
  categorizer-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

# Network configuration
networks:
  emailcat-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16