global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Email Categorizer Metrics
  - job_name: 'email-categorizer-metrics'
    static_configs:
      - targets: ['metrics-exporter:8000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (Container Metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Web Interface Health
  - job_name: 'web-interface'
    static_configs:
      - targets: ['web-interface:8082']
    scrape_interval: 60s
    metrics_path: /api/system-status

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093