name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile Python (syntax check)
        run: |
          python -m compileall -q .

      - name: Lint (basic)
        run: |
          python - <<'PY'
import os, sys
print('Repo contains', len([p for p in os.listdir('.') if p]), 'top-level items')
PY